---
# defaults file for cis-security see variable descriptions in security-rollup/README.md

### Mandatory Access controls
## Red Hat and Red Hat clones using selinux
selinux: "enforcing"            # Options are enforcing, permissive, and disabled. Control is 'enforcing'
selinux_policy: "targeted"      # Options are targeted, minimum, or mls. Control has no default
crypto_policy: "DEFAULT"        # Options are DEFAULT, FIPS, or LEGAC

## Ubuntu, ubuntu clones, and SLES using apparbor
apparmor_level: "enforce"     # Set all profiles in /etc/apparmor.d/* to this level. Options are enforce or complain

time_service: "chrony"             # Option for RHEL7/Ubuntu only. RHEL8 only ships with chrony and this variable is not used
                                # Choices are 'ntp' or chrony'. For Ubuntu, this can also accept 'none' as an option to use only systemd timedatectl
time_server: "2.rhel.pool.ntp.org" # Time server for ntp, chrony, or timedatectl

sudo_log: "/var/log/sudoers"    # log file for sudo

# Yum repos and system updates
update_system: false            # Update the system to the latest during the role run
gpgcheck: true                  # Enable GPG checks on ALL repos
enable_audit: true              # Enable auditing of processes and filesystem changes
audit_backlog_limit: 8192       # RHEL default is 8MB backlog limit

# Server roles, setting any of the variables to false will remove the default RHEL packages for that service.
#  Setting them to true will not remove them, but will not set them up.
dhcp_server: false
dns_server: false
email_server: false             # If set to true, and the packages exist, it will set mail relay to local only
ftp_server: false
http_server: false
nfs_server: false
proxy_server: false
smb_server: false
tftp_server: false              # Option for RHEL7 only

log_host: false                 # Whether this machine will host rsyslog messages for other machines
log_port: 514
log_file_size: 8                # RHEL default is 8MB, control has no default
#rsyslog_file:                  # Uncomment to copy file listed to /etc/rsyslog.d

# Desktop roles, see 'Server roles' above.
ypbind: false
graphical_interface: false      # Whether to disable the GDM greeter service. The service will disabled on 'false'

# network security settings
enable_ipv6: false
tcpwrappers: false              # RHEL 7 control only
enable_firewall: firewalld      # supported values are firewalld or iptables
firewalld_default_zone: public
motd_file: "banner"             # File location by default in 'files' directory
issue_file: "issue"             # File location by default in 'files' directory
issue.net_file: "issue"         # File location by default in 'files' diretory
ipv6_disable: true

# SSH Server settings
ssh_log_level: INFO             # Control is INFO or VERBOSE. Stricter is not approved and more verbose exposes user info
ssh_max_auth_tries: 4           # Control is 4 retries
ssh_mac_list: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com" #RHEL7 only control
ssh_ciphers_list: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr" # Ubuntu control only
ssh_kex_list: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" # Ubuntu control only
ssh_alive_interval: 300         # Control is 5 minutes
ssh_alive_count_max: 0          # Control is 0 count
ssh_grace_time: 60              # Control is for 60 seconds or less
ssh_max_sessions: 4             # Control is 4 sessions from a single host
ssh_login_banner: issue.net     # a file with no path will exist in the role's files directory, an absolute path will exist on the control host

# Password settings, all settings below match controls
password_min_length: 14
password_req_digit: true
password_req_upper: true
password_req_lower: true
password_req_special: true
password_min_days: 7
password_expire_days: 365
password_warning_days: 7
password_inactive_lock_days: 30

# Environtment settings, all settings below match controls
shell_timeout: 900
default_umask: "027"            # Control is 027 or more strict


