---
# defaults file for cis-security see variable descriptions in security-rollup/README.md

### Mandatory Access controls
## Red Hat and Red Hat clones using selinux
selinux: "enforcing"            # Options are enforcing, permissive, and disabled. Control is 'enforcing'
selinux_policy: "targeted"      # Options are targeted, minimum, or mls. Control has no default
crypto_policy: "DEFAULT"        # Options are DEFAULT, FIPS, or LEGAC

## Ubuntu, ubuntu clones, and SLES using apparbor
apparmor_level: "enforce"     # Set all profiles in /etc/apparmor.d/* to this level. Options are enforce or complain

time_service: "chrony"             # Option for RHEL7/Ubuntu only. RHEL8 only ships with chrony and this variable is not used
                                # Choices are 'ntp' or chrony'. For Ubuntu, this can also accept 'none' as an option to use only systemd timedatectl
time_server: "2.rhel.pool.ntp.org" # Time server for ntp, chrony, or timedatectl

sudo_log: "/var/log/sudoers"    # log file for sudo

# AIDE configuration settings
aide_db_name:  "/var/lib/aide/aide.db.gz"        # Database name that AIDE will look for for comparison
aide_new_db_name: "/var/lib/aide/aide.db.new.gz" # Database name created during an --init run
aide_gzip: "yes"                              # 'yes' or 'no' to enable gzip compression on database

# Yum repos and system updates
update_system: false            # Update the system to the latest during the role run
gpgcheck: true                  # Enable GPG checks on ALL repos
enable_audit: true              # Enable auditing of processes and filesystem changes
audit_backlog_limit: 8192       # RHEL default is 8MB backlog limit

# Server roles, setting any of the variables to false will remove the default RHEL packages for that service.
#  Setting them to true will not remove them, but will not set them up.
dhcp_server: false
dns_server: false
email_server: false             # If set to true, and the packages exist, it will set mail relay to local only
ftp_server: false
http_server: false
nfs_server: false
proxy_server: false
smb_server: false
tftp_server: false              # Option for RHEL7 only

log_host: false                 # Whether this machine will host rsyslog messages for other machines
log_port: 514
log_file_size: 8                # RHEL default is 8MB, control has no default
#rsyslog_file:                  # Uncomment to copy file listed to /etc/rsyslog.d

# Desktop roles, see 'Server roles' above.
ypbind: false
graphical_interface: false      # Whether to disable the GDM greeter service. The service will disabled on 'false'

# network security settings
enable_ipv6: false
tcpwrappers: false              # RHEL 7 control only
enable_firewall: firewalld      # supported values are firewalld or iptables
firewalld_default_zone: public
motd_file: "banner"             # File location by default in 'files' directory
issue_file: "issue"             # File location by default in 'files' directory
issue.net_file: "issue"         # File location by default in 'files' diretory
ipv6_disable: true

# SSH Server settings
ssh_log_level: INFO             # Control is INFO or VERBOSE. Stricter is not approved and more verbose exposes user info
ssh_max_auth_tries: 4           # Control is 4 retries
ssh_mac_list: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com" #RHEL7 only control
ssh_ciphers_list: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr" # Ubuntu control only
ssh_kex_list: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" # Ubuntu control only
ssh_alive_interval: 300         # Control is 5 minutes
ssh_alive_count_max: 0          # Control is 0 count
ssh_grace_time: 60              # Control is for 60 seconds or less
ssh_max_sessions: 4             # Control is 4 sessions from a single host
ssh_login_banner: issue.net     # a file with no path will exist in the role's files directory, an absolute path will exist on the control host

# Password and account settings, all settings below match controls
password_min_length: 14
password_req_digit: true
password_req_upper: true
password_req_lower: true
password_req_special: true
password_min_days: 7              # Windows has this control listed as 1 day
password_expire_days: 365         # Windows has this control listed as 24 days
password_warning_days: 7          # Windows has this control listed as 'between 5 and 14 days'
password_inactive_lock_days: 30
password_history: 24              # number of passwords to remember. Windows only setting
account_lockout_duration: 15      # Windows only setting
account_lockout_threshold: 10     # Windows only setting
account_reset_duration: 15        # Windows only setting
cached_logins: 4                  # Windows only setting: Number of login credentials to cache
enable_guest: false               # Windows only setting: enable guest account
rename_guest: "Guest"             # Windows only setting: name of guest account. Will have no effect if enable_gues variable is set to false
enable_Administrator: true        # Windows only setting: enable Administrator account
rename_Administrator: "Administrator" # Windows only setting: name of Administrator account. Will have no effect if enable_Administrator variable is set to false
dc_network_logon_right:              # Windows only setting: Users that have access to log on from the network (domain controllers)
  - "Administrators"
  - "Authenticated Users"
  - "ENTERPRISE DOMAIN CONTROLLERS"
ms_network_logon_right:              # Windows only setting: Users that have access to log on from the network (member servers and standalone servers)
  - "Administrators"
  - "Authenticated Users"
local_logon_right:                # Windows only setting: Users that have access to log onto the console
  - "Administrators"
dc_rds_logon_right:               # Windows only setting: Users that have access to log onto the system through Remote Desktop Services (domain controller)
  - "Administrators"
  - "Remote Desktop Users"
ms_rds_logon_right:               # Windows only setting: Users that have access to log onto the system through Remote Desktop Services (member or standalone server)
  - "Administrators"
adjust_memory_quotas:             # Windows only setting: Users that can adjust the memory quotas for a process
  - "Administrators"
  - "LOCAL SERVICE"
  - "NETWORK SERVICE"
backup_operators:                 # Windows only setting: Users that can backup files and diretories via a backup application
  - "Administrators"
time_operators:                   # Windows only setting: Users that can set the system time
  - "Administrators"
  - "LOCAL SERVICE"
dc_symbolic_link_right:              # Windows only setting: Users that can create symbolic links.
  - "Administrators"
ms_symbolic_link_right:              # Windows only setting: Users that can create symbolic links. If Hyper-V is installed, this should include "Virtual Machines"
  - "Administrators"
  - 'NT VIRTUAL MACHINE\Virtual Machines'
max_machine_account_days: 30      # Windows only setting: Maximum number of days a machine can keep its password before changing. A zero here will
                                  #  automatically be changed to 30 by the task to force some password rotation

# Environtment settings, all settings below match controls
shell_timeout: 900
default_umask: "027"              # Control is 027 or more strict
inactivity_timeout: 900           # Windows only setting: Number of seconds before screen saver. A zero here will default to 900 for some security

smart_card_removal: 1             # Windows only setting. what do do when a smart card used for authentication is removed.
                                  # Options that can be set in or take effect:
                                  #  1 - Lock Workstation
                                  #  2 - Force Logoff
                                  #  3 - Disconnect if a Remote Desktop Services session
smb_inactivity_minutes: 15        # Windows only setting. Minutes until server suspends SMB connection due to inactivity
spn_level: 1                      # Windows only setting. level of validation with shared folders the server performs on the service principal name
                                  # Options that can be set in or take effect:
                                  #  1 - Accept if provided by client
                                  #  2 - Required from client
ldap_client_signing: 1            # Windows only setting. Sign ldap client communications
                                  # Options that can be set to take effect:
                                  #  1 - Negotiate signing
                                  #  2 - Require signing
uac_prompt_for_consent_admin: 2   # Windows only setting. When to prompt admins for elevated Admin Approval Mode
                                  #  0 - Elevate without prompting
                                  #  1 - Prompt for credentials on the secure desktop
                                  #  2 - Prompt for consent on the secure desktop (default)
                                  #  3 - Prompt for credentials
                                  #  4 - Prompt for consent
                                  #  5 - Prompt for consent for non-Windows binaries
uac_prompt_for_consent_user: 3    # Windows only setting. When to prompt users for elevated Admin Approval Mode
                                  #  0 - Automatically deny elevation requests
                                  #  1 - Prompt for credentials on the secure desktop
                                  #  3 - Prompt for credentials
screensaver_grace_time: 0         # Windows only setting. Seconds from screen saver start until computer locks
win_application_log_size: "32768" # Windows only setting. Max application event log file size
win_security_log_size: "196608"   # Windows only setting. Max security event log file size
win_setup_log_size: "32768"      # Windows only setting. Max setup event log file size
win_system_log_size: "32768"      # Windows only setting. Max setup event log file size
disable_automatic_updates: "0"     # Windows only setting. Disable automatic updates. Set to '1' to disable automatic updates. (Choose if using 3rd party update systems)
au_update_options: "4"            # Windows only setting. Configure automatic updates. Possible values
                                  #  2 - Notify for download and auto install (Notify before downloading any updates)
                                  #  3 - Auto download and notify for install (Download the updates automatically and notify when they are ready to be installed.) (Default setting)
                                  #  4 - Auto download and schedule the install (Automatically download updates and install them on the schedule specified below.))
                                  #  5 - Allow local admin to choose setting (Leave decision on above choices up to the local Administrators (Not Recommended))
au_update_day: "0"                # Windows only setting. Configure which day automatic updates will be installed.
                                  #  Only takes effect if "automatic_updates" == "4". Possible values
                                  #  0 - Every delay
                                  #  1 - Every Sunday
                                  #  2 - Every Monday
                                  #  3 - Every Tuesday
                                  #  4 - Every Wednesday
                                  #  5 - Every Thursday
                                  #  6 - Every Friday
                                  #  7 - Every Saturday
au_update_time: "3"               # Windows only setting. Configure what time automatic updates will be installed.
                                  #  Only takes effect if "automatic_updates" == "4". This is the hour portion of the
                                  #   time only. "3" means 03:00am. Set this value to '24' for windows to automatically pick a time